### ISSUE TITLE
when running "gem install shadowsocks",encounter error

### ISSUE THREAD

**Issue by luckypoem** [Sen/shadowsocks-ruby#1]
hi.

root@VM:~# ruby -v
ruby 2.0.0p647 (2015-08-18 revision 51631) [x86_64-linux]
root@VM:~#
root@VM:~# gem install shadowsocks
ERROR:  Loading command: install (LoadError)
    cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
root@VM:~#

how to fix it?
tks!

**Comment by Sen** [comment]
strange, seems like can't find openssl by your side, could you check openssl exists or not?

**Comment by luckypoem** [comment]
root@VM:~# apt-get install openssl 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
openssl is already the newest version.
openssl set to manually installed.
The following packages were automatically installed and are no longer required:
  apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
root@VM:~#

已经装了openssl啊。

**Comment by Sen** [comment]
那你能在irb里require 'openssql' 吗?

**Comment by luckypoem** [comment]
hi.
不好意思，不太明白你的意思，具体在vps 里运行什么命令进行检测？

**Comment by Sen** [comment]
请问你是ruby新手是吗？
我现在想是你的ruby感觉有点问题，请问你是用什么方式进行安装的？

**Comment by luckypoem** [comment]
hi.
我知道是什么原因了。
我是编译安装ruby的。
cd ~/ruby-2.0.0-p647/ext/
cd openssl
ruby extconf.rb
make
make install

cd ~/ruby-2.0.0-p647/ext/zlib
ruby extconf.rb
make
make install

然后就可正常的运行gem install shadowsocks

**Comment by Sen** [comment]
是的，ruby中的openssl模块没有安装好
下次建议使用rvm/rbenv进行编译安装
